// storage_service.dart
// Handles all local storage setup (Hive) — opening boxes, registering
// adapters. Called once at app startup from main.dart.

import 'package:hive_flutter/hive_flutter.dart';
import '../models/progress.dart';

class StorageService {
  static const String progressBoxName = 'progressBox';

  // Call this once, before runApp(), to prepare Hive for use.
  static Future<void> init() async {
    await Hive.initFlutter();
    Hive.registerAdapter(ProgressAdapter()); // generated by build_runner in Step 2
    await Hive.openBox<Progress>(progressBoxName);
  }

  // Convenience getter to access the open box from anywhere.
  static Box<Progress> get progressBox => Hive.box<Progress>(progressBoxName);
}