// app_meta.dart
// Holds app-level metadata that isn't tied to any single word — streak
// tracking, plus (added this session) daily reminder preferences.
// Separate from Progress (which is per-word) since this represents one
// record for the whole app, not one per word.
//
// Only ONE instance of this should ever exist in its Hive box (always
// saved/read under the same fixed key — see StorageService).
import 'package:hive/hive.dart';
part 'app_meta.g.dart'; // auto-generated by Hive's code generator (next step)

@HiveType(typeId: 2) // typeId 0 = Progress, 1 = Mnemonic — 2 is free
class AppMeta extends HiveObject {
  @HiveField(0)
  int currentStreak;

  @HiveField(1)
  int longestStreak;

  @HiveField(2)
  DateTime? lastOpenDate; // date only (time zeroed out) — see provider logic

  // Added this session for the daily reminder feature. defaultValue is set
  // so any AppMeta record saved before this change (which won't have these
  // fields in storage) loads safely instead of crashing — same lesson as
  // the Progress model field-add in Session 2.
  @HiveField(3, defaultValue: false)
  bool reminderEnabled;

  @HiveField(4, defaultValue: 20)
  int reminderHour;

  @HiveField(5, defaultValue: 0)
  int reminderMinute;

  AppMeta({
    this.currentStreak = 0,
    this.longestStreak = 0,
    this.lastOpenDate,
    this.reminderEnabled = false,
    this.reminderHour = 20,
    this.reminderMinute = 0,
  });
}