// app_meta.dart
// Holds app-level metadata that isn't tied to any single word — currently
// just streak tracking. Separate from Progress (which is per-word) since
// this represents one record for the whole app, not one per word.
//
// Only ONE instance of this should ever exist in its Hive box (always
// saved/read under the same fixed key — see StorageService).

import 'package:hive/hive.dart';

part 'app_meta.g.dart'; // auto-generated by Hive's code generator (next step)

@HiveType(typeId: 2) // typeId 0 = Progress, 1 = Mnemonic — 2 is free
class AppMeta extends HiveObject {
  @HiveField(0)
  int currentStreak;

  @HiveField(1)
  int longestStreak;

  @HiveField(2)
  DateTime? lastOpenDate; // date only (time zeroed out) — see provider logic

  AppMeta({
    this.currentStreak = 0,
    this.longestStreak = 0,
    this.lastOpenDate,
  });
}