// mnemonic.dart
// Represents one personal mnemonic entry (text or voice) the user wrote
// for a specific word. Stored permanently in Hive, separate from Progress
// (SRS scheduling) since this is personal content, not review scheduling.

import 'package:hive/hive.dart';

part 'mnemonic.g.dart'; // auto-generated by build_runner, same as progress.g.dart

@HiveType(typeId: 1) // typeId 0 is already used by Progress — must be unique
class Mnemonic extends HiveObject {
  @HiveField(0)
  String word;

  @HiveField(1)
  String? textNote; // personal text mnemonic, if written

  @HiveField(2)
  String? audioFilePath; // local file path to a recorded voice note, if any

  @HiveField(3)
  DateTime createdAt;

  Mnemonic({
    required this.word,
    this.textNote,
    this.audioFilePath,
    required this.createdAt,
  });
}