// progress.dart
// Tracks a user's LEARNING PROGRESS for one word — separate from the word's
// content itself (see word.dart). This is what actually gets saved in Hive,
// since it changes over time as the user reviews words.
//
// Implements true spaced repetition (SRS): correct answers push the next
// review further out; wrong answers reset it. See intervalDays/correctStreak.

import 'package:hive/hive.dart';

part 'progress.g.dart'; // auto-generated by Hive's code generator (next step)

@HiveType(typeId: 0)
class Progress extends HiveObject {
  @HiveField(0)
  String word; // matches the "word" field in word.dart, links the two models

  @HiveField(1)
  DateTime? lastReviewed;

  @HiveField(2)
  int intervalDays; // how many days until next review is due

  @HiveField(3)
  int correctStreak; // consecutive correct answers in Word Detective

  @HiveField(4)
  DateTime? nextReviewDue;

  @HiveField(5)
  bool learned; // true once the word has been reviewed enough to feel "mastered"

  @HiveField(6)
  String? userMnemonic; // personal text mnemonic, if the user wrote one

  @HiveField(7)
  String? voiceNoteId; // reference to a saved voice recording, if any

  @HiveField(8)
  int totalAttempts;

  @HiveField(9)
  int correctAttempts;

  Progress({
    required this.word,
    this.lastReviewed,
    this.intervalDays = 1,
    this.correctStreak = 0,
    this.nextReviewDue,
    this.learned = false,
    this.userMnemonic,
    this.voiceNoteId,
    this.totalAttempts = 0,
    this.correctAttempts = 0,
  });

  // Call this when the user answers correctly in Word Detective.
  // Interval grows: 1 -> 2 -> 5 -> 10 -> 20 days (caps at 20).
  void markCorrect() {
    totalAttempts += 1;
    correctAttempts += 1;
    correctStreak += 1;
    lastReviewed = DateTime.now();
    if (intervalDays == 1) {
      intervalDays = 2;
    } else if (intervalDays == 2) {
      intervalDays = 5;
    } else if (intervalDays == 5) {
      intervalDays = 10;
    } else {
      intervalDays = 20;
    }
    nextReviewDue = DateTime.now().add(Duration(days: intervalDays));
    if (correctStreak >= 3) learned = true; // mastered after 3 correct in a row
  }

  // Call this when the user answers incorrectly. Resets the spacing —
  // the word needs to be seen again soon, not in weeks.
  void markIncorrect() {
    totalAttempts += 1;
    correctStreak = 0;
    intervalDays = 1;
    lastReviewed = DateTime.now();
    nextReviewDue = DateTime.now().add(const Duration(days: 1));
    learned = false;
  }
}